version: "1.0"

profiles:
  - name: "CodeMetrics"
    checks:
      - id: "code.metrics"
        enabled: true

run:
  projectRoot: ./ # Root-Verzeichnis des Projekts
  cacheDir: ./.qodana-cache # Cache-Verzeichnis
  outputDir: ./qodana-report # Verzeichnis für Berichte

report:
  format: ["html", "json"] # Formate der Berichte

metrics:
  - enabled: true
    include:
      - "Code Complexity"
      - "Code Duplication"
      - "Code Coverage"
    thresholds:
      "Code Complexity": 10 # Maximal erlaubte Komplexität
      "Code Duplication": 5 # Maximaler Prozentsatz für Duplikate
      "Code Coverage": 80 # Mindestabdeckung in Prozent

tools:
  - name: "Python"
    enabled: true

filters:
  exclude:
    - "**/test/**"
    - "**/build/**"
    - "**/node_modules/**"

failThreshold:
  - metric: "Code Complexity"
    max: 10
  - metric: "Code Duplication"
    max: 5
  - metric: "Code Coverage"
    min: 80
